
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'Determinante Preposicion Sustantivo VerboOracion : SN SVSN : Determinante SustantivoSN : DeterminanteSV : Verbo SPrepSPrep : Preposicion SN'
    
_lr_action_items = {'Determinante':([0,8,],[2,2,]),'Verbo':([2,3,4,],[-3,5,-2,]),'Preposicion':([5,],[8,]),'Sustantivo':([2,],[4,]),'$end':([1,2,4,6,7,9,],[0,-3,-2,-1,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Oracion':([0,],[1,]),'SPrep':([5,],[7,]),'SN':([0,8,],[3,9,]),'SV':([3,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Oracion","S'",1,None,None,None),
  ('Oracion -> SN SV','Oracion',2,'p_Oracion','Estructura4.py',27),
  ('SN -> Determinante Sustantivo','SN',2,'p_SN','Estructura4.py',35),
  ('SN -> Determinante','SN',1,'p_SN1','Estructura4.py',42),
  ('SV -> Verbo SPrep','SV',2,'p_SV','Estructura4.py',48),
  ('SPrep -> Preposicion SN','SPrep',2,'p_SPrep','Estructura4.py',55),
]
